# Generated by Django 3.1.2 on 2020-10-08 13:32

import datetime
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('name_history', django.contrib.postgres.fields.jsonb.JSONField()),
                ('description', models.CharField(max_length=1000)),
                ('description_history', django.contrib.postgres.fields.jsonb.JSONField()),
                ('state', models.CharField(choices=[('New', 'Новая'), ('In progress', 'В работе'), ('Done', 'Завершенная')], default='New', max_length=12)),
                ('state_history', django.contrib.postgres.fields.jsonb.JSONField()),
                ('start_time', models.DateTimeField(default=datetime.datetime(2020, 10, 8, 13, 32, 23, 16187))),
                ('finish_time', models.DateTimeField()),
                ('finish_time_history', django.contrib.postgres.fields.jsonb.JSONField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
